title: Must IT 블로그
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://TaeseongYun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: TaeseongYun # add your name
author-img: taeseong-yun.jpg # add your photo
about-author: 패션과 코딩에 관심이 많은 IT 개발자 # add description
social-twitter: # add your Twitter handle
social-facebook: profile.php?id=100003052989677 # add your Facebook handle
social-github: TaeseongYun # add your Github handle
social-linkedin: taeseong-yoon-525976190/ # add your Linkedin handle
social-email: yts0646@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
